// Default A-Z word lists (2-3 toddler words per letter).
window.DEFAULT_WORDS = {
  A: [{en:'apple',zh:'苹果'},{en:'ant',zh:'蚂蚁'},{en:'airplane',zh:'飞机'}],
  B: [{en:'ball',zh:'球'},{en:'bear',zh:'熊'},{en:'banana',zh:'香蕉'}],
  C: [{en:'cat',zh:'猫'},{en:'car',zh:'汽车'},{en:'cake',zh:'蛋糕'}],
  D: [{en:'dog',zh:'狗'},{en:'duck',zh:'鸭子'},{en:'door',zh:'门'}],
  E: [{en:'egg',zh:'鸡蛋'},{en:'elephant',zh:'大象'},{en:'eye',zh:'眼睛'}],
  F: [{en:'fish',zh:'鱼'},{en:'frog',zh:'青蛙'},{en:'flower',zh:'花'}],
  G: [{en:'grapes',zh:'葡萄'},{en:'giraffe',zh:'长颈鹿'},{en:'gift',zh:'礼物'}],
  H: [{en:'hat',zh:'帽子'},{en:'horse',zh:'马'},{en:'house',zh:'房子'}],
  I: [{en:'ice cream',zh:'冰淇淋'},{en:'igloo',zh:'冰屋'}],
  J: [{en:'juice',zh:'果汁'},{en:'jellyfish',zh:'水母'}],
  K: [{en:'kite',zh:'风筝'},{en:'key',zh:'钥匙'},{en:'koala',zh:'考拉'}],
  L: [{en:'lion',zh:'狮子'},{en:'lemon',zh:'柠檬'},{en:'leaf',zh:'叶子'}],
  M: [{en:'moon',zh:'月亮'},{en:'monkey',zh:'猴子'},{en:'milk',zh:'牛奶'}],
  N: [{en:'nose',zh:'鼻子'},{en:'nest',zh:'鸟窝'}],
  O: [{en:'orange',zh:'橙子'},{en:'owl',zh:'猫头鹰'},{en:'octopus',zh:'章鱼'}],
  P: [{en:'pig',zh:'猪'},{en:'penguin',zh:'企鹅'},{en:'pizza',zh:'披萨'}],
  Q: [{en:'queen',zh:'女王'},{en:'quilt',zh:'被子'}],
  R: [{en:'rabbit',zh:'兔子'},{en:'rainbow',zh:'彩虹'},{en:'rocket',zh:'火箭'}],
  S: [{en:'sun',zh:'太阳'},{en:'star',zh:'星星'},{en:'sock',zh:'袜子'}],
  T: [{en:'tiger',zh:'老虎'},{en:'tree',zh:'树'},{en:'train',zh:'火车'}],
  U: [{en:'umbrella',zh:'雨伞'},{en:'unicorn',zh:'独角兽'}],
  V: [{en:'van',zh:'面包车'},{en:'violin',zh:'小提琴'}],
  W: [{en:'whale',zh:'鲸鱼'},{en:'water',zh:'水'},{en:'watch',zh:'手表'}],
  X: [{en:'xylophone',zh:'木琴'},{en:'x-ray',zh:'X光'}],
  Y: [{en:'yo-yo',zh:'溜溜球'},{en:'yogurt',zh:'酸奶'}],
  Z: [{en:'zebra',zh:'斑马'},{en:'zoo',zh:'动物园'}]
};
