// Built-in word -> emoji mapping (lowercase English). Used by the card generator.
window.EMOJI_MAP = {
  // animals
  ant:'🐜', bear:'🐻', bee:'🐝', bird:'🐦', butterfly:'🦋', bug:'🐛', camel:'🐫', cat:'🐱', kitten:'🐱', chick:'🐤', chicken:'🐔', hen:'🐔', rooster:'🐓', cow:'🐮', crab:'🦀', crocodile:'🐊', alligator:'🐊', deer:'🦌', dinosaur:'🦕', dino:'🦕', dog:'🐶', puppy:'🐶', dolphin:'🐬', donkey:'🫏', duck:'🦆', eagle:'🦅', elephant:'🐘', fish:'🐟', flamingo:'🦩', fox:'🦊', frog:'🐸', giraffe:'🦒', goat:'🐐', gorilla:'🦍', hamster:'🐹', hedgehog:'🦔', hippo:'🦛', hippopotamus:'🦛', horse:'🐴', pony:'🐴', kangaroo:'🦘', koala:'🐨', ladybug:'🐞', lion:'🦁', lizard:'🦎', llama:'🦙', lobster:'🦞', monkey:'🐵', mouse:'🐭', octopus:'🐙', owl:'🦉', ox:'🐂', panda:'🐼', parrot:'🦜', peacock:'🦚', penguin:'🐧', pig:'🐷', rabbit:'🐰', bunny:'🐰', raccoon:'🦝', rat:'🐀', rhino:'🦏', seal:'🦭', shark:'🦈', sheep:'🐑', lamb:'🐑', shrimp:'🦐', snail:'🐌', snake:'🐍', spider:'🕷️', squid:'🦑', squirrel:'🐿️', swan:'🦢', tiger:'🐯', turkey:'🦃', turtle:'🐢', tortoise:'🐢', unicorn:'🦄', whale:'🐳', wolf:'🐺', worm:'🪱', zebra:'🦓', yak:'🐃', bat:'🦇', beaver:'🦫', bison:'🦬', mammoth:'🦣', sloth:'🦥', otter:'🦦', skunk:'🦨', dragon:'🐉', jellyfish:'🪼', goose:'🪿', moose:'🫎', 'polar bear':'🐻‍❄️', 'teddy bear':'🧸', teddy:'🧸',
  // fruits & food
  apple:'🍎', avocado:'🥑', banana:'🍌', blueberry:'🫐', cherry:'🍒', coconut:'🥥', grape:'🍇', grapes:'🍇', kiwi:'🥝', lemon:'🍋', mango:'🥭', melon:'🍈', orange:'🍊', peach:'🍑', pear:'🍐', pineapple:'🍍', strawberry:'🍓', watermelon:'🍉', tomato:'🍅', carrot:'🥕', corn:'🌽', broccoli:'🥦', cucumber:'🥒', eggplant:'🍆', potato:'🥔', pepper:'🫑', mushroom:'🍄', onion:'🧅', garlic:'🧄', peanut:'🥜', nut:'🥜', chestnut:'🌰', bread:'🍞', cake:'🍰', candy:'🍬', lollipop:'🍭', cheese:'🧀', cookie:'🍪', donut:'🍩', doughnut:'🍩', egg:'🥚', fries:'🍟', hamburger:'🍔', burger:'🍔', 'hot dog':'🌭', hotdog:'🌭', 'ice cream':'🍦', icecream:'🍦', jam:'🍓', jelly:'🍮', juice:'🧃', milk:'🥛', noodles:'🍜', noodle:'🍜', pizza:'🍕', popcorn:'🍿', rice:'🍚', sandwich:'🥪', soup:'🍲', sushi:'🍣', dumpling:'🥟', chocolate:'🍫', honey:'🍯', pie:'🥧', pancake:'🥞', water:'💧', tea:'🍵', coffee:'☕', yogurt:'🥛', butter:'🧈', salt:'🧂', meat:'🍖', bacon:'🥓', taco:'🌮', cupcake:'🧁', pudding:'🍮', olive:'🫒', bean:'🫘', beans:'🫘', 
  // body
  arm:'💪', ear:'👂', eye:'👁️', eyes:'👀', face:'🙂', finger:'☝️', foot:'🦶', feet:'🦶', hair:'💇', hand:'✋', head:'🙂', heart:'❤️', knee:'🦵', leg:'🦵', lips:'👄', mouth:'👄', nose:'👃', thumb:'👍', tooth:'🦷', teeth:'🦷', tongue:'👅', brain:'🧠', bone:'🦴', 
  // people & family
  baby:'👶', boy:'👦', girl:'👧', man:'👨', woman:'👩', mom:'👩', mommy:'👩', mother:'👩', mum:'👩', dad:'👨', daddy:'👨', father:'👨', grandma:'👵', grandpa:'👴', family:'👪', friend:'🧑‍🤝‍🧑', king:'🤴', queen:'👸', prince:'🤴', princess:'👸', doctor:'🧑‍⚕️', nurse:'🧑‍⚕️', teacher:'🧑‍🏫', farmer:'🧑‍🌾', cook:'🧑‍🍳', chef:'🧑‍🍳', police:'👮', firefighter:'🧑‍🚒', astronaut:'🧑‍🚀', clown:'🤡', ghost:'👻', robot:'🤖', alien:'👽', angel:'👼', santa:'🎅', witch:'🧙', wizard:'🧙', fairy:'🧚', mermaid:'🧜', vampire:'🧛', zombie:'🧟', ninja:'🥷', pirate:'🏴‍☠️',
  // vehicles
  airplane:'✈️', plane:'✈️', ambulance:'🚑', bike:'🚲', bicycle:'🚲', boat:'⛵', bus:'🚌', car:'🚗', helicopter:'🚁', jeep:'🚙', motorcycle:'🏍️', rocket:'🚀', ship:'🚢', taxi:'🚕', tractor:'🚜', train:'🚂', truck:'🚚', van:'🚐', scooter:'🛴', skateboard:'🛹', 'fire truck':'🚒', firetruck:'🚒', 'police car':'🚓', submarine:'🤿', balloon:'🎈', 'hot air balloon':'🎈', canoe:'🛶', kayak:'🛶', 
  // nature & weather
  sun:'☀️', moon:'🌙', star:'⭐', cloud:'☁️', rain:'🌧️', rainbow:'🌈', snow:'❄️', snowman:'⛄', wind:'🌬️', lightning:'⚡', thunder:'⛈️', umbrella:'☂️', fire:'🔥', tree:'🌳', flower:'🌸', rose:'🌹', tulip:'🌷', sunflower:'🌻', leaf:'🍃', leaves:'🍂', grass:'🌱', plant:'🪴', cactus:'🌵', mountain:'⛰️', volcano:'🌋', ocean:'🌊', sea:'🌊', wave:'🌊', island:'🏝️', beach:'🏖️', earth:'🌍', world:'🌍', globe:'🌍', rock:'🪨', stone:'🪨', shell:'🐚', seed:'🌱', wood:'🪵', log:'🪵', comet:'☄️', planet:'🪐', 
  // home & objects
  ball:'⚽', football:'🏈', soccer:'⚽', basketball:'🏀', baseball:'⚾', tennis:'🎾', bed:'🛏️', bell:'🔔', book:'📖', box:'📦', bag:'👜', backpack:'🎒', basket:'🧺', bath:'🛁', bathtub:'🛁', bucket:'🪣', brush:'🖌️', toothbrush:'🪥', broom:'🧹', candle:'🕯️', chair:'🪑', clock:'⏰', comb:'🪮', computer:'💻', crayon:'🖍️', cup:'🥤', mug:'☕', door:'🚪', doll:'🪆', drum:'🥁', gift:'🎁', present:'🎁', glasses:'👓', guitar:'🎸', hammer:'🔨', hat:'🎩', cap:'🧢', house:'🏠', home:'🏠', key:'🔑', kite:'🪁', lamp:'💡', light:'💡', 'light bulb':'💡', lock:'🔒', magnet:'🧲', map:'🗺️', mirror:'🪞', money:'💰', coin:'🪙', music:'🎵', necklace:'📿', nail:'💅', pen:'🖊️', pencil:'✏️', phone:'📱', telephone:'☎️', piano:'🎹', pillow:'🛏️', plate:'🍽️', puzzle:'🧩', queen_crown:'👑', crown:'👑', radio:'📻', ring:'💍', ruler:'📏', scissors:'✂️', shoe:'👟', shoes:'👟', sock:'🧦', socks:'🧦', shirt:'👕', 't-shirt':'👕', dress:'👗', skirt:'👗', pants:'👖', jeans:'👖', coat:'🧥', jacket:'🧥', scarf:'🧣', gloves:'🧤', glove:'🧤', boot:'👢', boots:'👢', sofa:'🛋️', couch:'🛋️', soap:'🧼', spoon:'🥄', fork:'🍴', knife:'🔪', bowl:'🥣', bottle:'🍼', table:'🪑', television:'📺', tv:'📺', tent:'⛺', toilet:'🚽', toy:'🧸', toys:'🧸', trumpet:'🎺', violin:'🎻', watch:'⌚', window:'🪟', 'yo-yo':'🪀', yoyo:'🪀', zipper:'🤐', xylophone:'🎼', 'x-ray':'🩻', xray:'🩻', camera:'📷', flag:'🚩', ladder:'🪜', letter:'✉️', mail:'📬', envelope:'✉️', paint:'🎨', paper:'📄', picture:'🖼️', sponge:'🧽', tape:'📼', towel:'🧻', button:'🔘', bubble:'🫧', bubbles:'🫧', game:'🎮', dice:'🎲', block:'🧱', blocks:'🧱', brick:'🧱', castle:'🏰', school:'🏫', hospital:'🏥', park:'🏞️', zoo:'🦁', farm:'🚜', shop:'🏪', store:'🏪', bridge:'🌉', road:'🛣️', swing:'🛝', slide:'🛝', anchor:'⚓', axe:'🪓', saw:'🪚', 'teddy-bear':'🧸', igloo:'🧊', ice:'🧊', 'ice cube':'🧊', jar:'🫙', jet:'✈️', web:'🕸️', wheel:'🛞', yarn:'🧶', vase:'🏺', violet:'🪻', vest:'🦺', volleyball:'🏐', quilt:'🛏️', question:'❓', 'question mark':'❓', quiet:'🤫', quack:'🦆', nest:'🪺', net:'🥅', needle:'🪡', moon_cake:'🥮', mooncake:'🥮', lantern:'🏮', 
  // feelings / actions / misc
  happy:'😀', sad:'😢', smile:'😊', cry:'😭', laugh:'😂', angry:'😠', sleep:'😴', sleepy:'😴', tired:'🥱', love:'❤️', kiss:'😘', hug:'🤗', yes:'👍', no:'🙅', hello:'👋', hi:'👋', bye:'👋', goodbye:'👋', 'thank you':'🙏', please:'🙏', run:'🏃', walk:'🚶', jump:'🤸', dance:'💃', swim:'🏊', sing:'🎤', eat:'😋', drink:'🥤', play:'🧸', read:'📖', write:'✍️', clap:'👏', wave_hand:'👋', hot:'🥵', cold:'🥶', big:'🐘', small:'🐭', up:'⬆️', down:'⬇️', 'one':'1️⃣', two:'2️⃣', three:'3️⃣', four:'4️⃣', five:'5️⃣', six:'6️⃣', seven:'7️⃣', eight:'8️⃣', nine:'9️⃣', ten:'🔟', zero:'0️⃣',
  // colors
  red:'🔴', blue:'🔵', green:'🟢', yellow:'🟡', purple:'🟣', brown:'🟤', black:'⚫', white:'⚪', pink:'🩷', grey:'🩶', gray:'🩶'
};
